path:
  RAW_PATH: ./data/raw/
  PROCESSED_PATH: ./data/processed/
  FILES_PATH: ./research/files/
  TRAIN_MODEL_PATH: ./checkpoints/train_models/
  BEST_MODEL_PATH: ./checkpoints/best_model/
  OUTPUTS_PATH: ./outputs/


data:
  dataset: ./data/raw/breast-cancer.csv
  batch_size: 64
  split_size: 0.30

model:
  in_features: 30

trainer:
  epochs: 130
  lr: 0.01
  beta1: 0.5
  beta2: 0.999
  step_size: 10   # Lr_scheduler
  gamma: 0.1      # lr_scheduler
  adam: True
  SGD: False
  display: true
  lr_scheduler: False
