path:
  RAW_PATH: ./data/raw/
  PROCESSED_PATH: ./data/processed/
  FILES_PATH: ./research/files/


data:
  dataset: ./data/raw/breast-cancer.csv
  batch_size: 64
  split_size: 0.20

model:
  in_features: 30